---
- name: Clone EthStats repo
  git:
    repo: https://github.com/cubedro/eth-netstats
    dest: "{{ethstats_dir}}"

- name: Install eth-netstats
  npm:
    path: "{{ethstats_dir}}"

- name: Install grunt-cli
  npm:
    name: grunt-cli
    global: yes

- name: Build eth-netstats
  command: grunt
  args:
    chdir: "{{ethstats_dir}}"

- name: Install systemd script
  template:
    src: ethstats.service.j2
    dest: /etc/systemd/system/ethstats.service

- name: Enable and start EthStats service
  systemd:
    name: ethstats.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Clone eth-net-intelligence-api
  git:
    repo: https://github.com/cubedro/eth-net-intelligence-api
    dest: "{{ethstats_client_dir}}"

- name: Install eth-net-intelligence-api
  npm:
    path: "{{ethstats_client_dir}}"

- name: Configure eth-net-intelligence-api
  lineinfile:
    dest: "{{ethstats_client_dir}}/app.json"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: 'WS_SERVER', line: '    "WS_SERVER": "{{ws_server}}"' }
    - { regexp: 'WS_SECRET', line: '    "WS_SECRET": "{{ws_secret}}"' }
